var app = getApp();
var utils = require('../../utils/utils');
import upload_img from '../../assets/yinju/img/add/index'

Page({
	data:{
		height:'',
		//top-nav
		styleData2:{
			wrap:{
				backgroundColor:'#66B83D'
			},
			item:{
				padding:'0 30rpx',
				fontSize:'26rpx',
				height:'94rpx',
				color:'#fff'
			},
			line:{
				height:'4rpx',
				bottom:'10rpx',
				backgroundColor:'#fff'
			},
			active:{
				color:''
			}
		},
		//导航栏类型，是第几种类型的跳转
		type2:1,
		listData2:[
			{
				text:'咨询',
			},
			{
				text:'咨询',
			},
			{
				text:'咨询',
			},
			{
				text:'咨询',
			},
			{
				text:'咨询',
			},
			{
				text:'咨询',
			},
		],
		
		//footer
		//样式数据
		styleData:{
			//文字顶部到图片顶部的距离
			height:52,
			//文字样式
			text:{
				fontSize:20,
				color:'rgba(0,0,0,.6)',
			},
			//最外层标签的padding
			padding:0,
			//每行之间的距离
			marginBottom:'',
			//有多少行
			row:5,
			//每个图片是否大小一样
			same:false,
		},
		//内容数据
		//还差个activeIndex,以及每个被点击的后的图片。因为每个多个页面都会用到，因该把这些参数放在app.js中
		listData:[
			{
				//链接地址
				url:'../index/index',
				//文字内容
				text:'商城',
				src:'/utils/img/footer/1.png',
				active_img:'/utils/img/footer/5.png',
				//图片大小
				width:54,
				height:44,
			},
			{
				url:'../index/index',
				text:'商城',
				src:'/utils/img/footer/5.png',
				width:56,
				height:46,
			},
			{
				url:'../index/index',
				text:'',
				src:'/utils/img/footer/add.png',
				width:87,
				height:87,
				marginTop:-10
			},
			{
				url:'../index/index',
				text:'商城',
				src:'/utils/img/footer/3.png',
				width:47,
				height:47,
			},
			{
				url:'../index/index',
				text:'商城',
				src:'/utils/img/footer/7.png',
				width:46,
				height:46,
			},
		],
		location:'',
		upload_img:{
			list_data:{
				upload_img:{
					padding:'0 48rpx;',
					margin_right:-13,
				},
				//每一项的内容
				upload_img_item:{
					width:210,
					height:242,
					margin:'0 13rpx 13rpx 0'
				},
				//里面的图标
				icon_box:{
					width:66,
					height:66,
					src:upload_img.icon_add
				},
				text_box:{
					margin_top:26,
					font_size:24,
					color:'#A2A2A3',
					text:'上传'
				},
				delete:{
					width:33,
					src:upload_img.icon_delete,
					top:-9,
					right:-8,
				},
				//可上传的最大数
				count:9
			},
			imgs:[
				upload_img.local_img_1,
				"",
				"",
				"",
				"",
			],
		}
		
	},
	onLoad(){
		this.setData({
			height:app.data.height
		})
		
		this.getLocation();
	},
	getLocation() {
		var This = this;
		utils.getLocation(function(location){
			This.setData({
				location:location
			})
		});
	},
	get_nav_index(res){
		console.log(res.detail);
	}
})